### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/VORP-Hunting#10]
It works with a rat, but not with a deer, it always gives this error
[    script:vorp_core] SCRIPT ERROR: @vorp_core/server/class/sv_character.lua:197: attempt to perform arithmetic on a nil value (local 'quantity')
[    script:vorp_core] > addCurrency (@vorp_core/server/class/sv_character.lua:197)
[    script:vorp_core] > ref (@vorp_core/server/class/sv_character.lua:149)
[    script:vorp_core] > handler (@vorp_hunting/server/main.lua:30)
[ script:vorp_hunting] SCRIPT ERROR: error object is not a string
[ script:vorp_hunting] (nil stack trace)

Means THIS works here
[989669666]   = { name = "Rat", givenItem = { "meat" }, givenAmount = { 1 }, money = 100, gold = 0, rolPoints = 0, xp = 1 },
[1458540991]  = { name = "Raccoon", givenItem = { "pelt" }, givenAmount = { 2 }, money = 100, gold = 0, rolPoints = 0, xp = 1 },
[-1003616053] = { name = "Duck", givenItem = { "feathers" }, givenAmount = { 0 }, money = 100, gold = 0, rolPoints = 0, xp = 1 },

BUT NOT HERE
[1110710183]  = { name = "Deer", givenItem = { "meat" }, givenAmount = { 0 } },
[-1124266369] = { name = "Bear", givenItem = { "bearHeart", "bearClaws" }, givenAmount = { 1, 3 } }

**Comment by AndrewR3K** [comment]
Try it with the Deer/Bear having money/gold/relPoints/xp as well. these I believe are required.

Example
```
[1110710183] = { name = "Deer", givenItem = { "meat" }, givenAmount = { 0 }, money = 0, gold = 0, rolPoints = 0, xp = 1 },
[-1124266369] = { name = "Bear", givenItem = { "bearHeart", "bearClaws" }, givenAmount = { 1, 3 }, money = 0, gold = 0, rolPoints = 0, xp = 1 }
```

**Comment by AndrewR3K** [comment]
Let me know if that works for you, I'll update and submit a pr shortly.

**Comment by RizzooTv** [comment]
Yes, that's how it works, I could have figured it out :) I thought the example in the config without money etc. must work without it, but it doesn't matter that's how it works, just set everything to 0

I thank you again

**Comment by outsider31000** [comment]
If you do that then disable below other wise theres to places giving money  to be honest i would add everything on the top .

**Comment by RizzooTv** [comment]
Well at the butcher there should be money ;) above you get items and at the butcher you get money, it works fine for me now.

**Comment by outsider31000** [comment]
Ok great
