### ISSUE TITLE
small animals bug

### ISSUE THREAD

**Issue by Sina30** [VORPCORE/VORP-Hunting#14]
You don't get a notification for small animals if you got an item and you don't get any items in the inventory either

**Comment by DerHobbs** [comment]
Download the current version again and enter everything CORRECTLY into the config, it works wonderfully, look here

https://streamable.com/m2e4cu

**Comment by Sina30** [comment]
Have you ever tried it with a rat because you don't get anything with the rabbits I have it with the normal animals

**Comment by DerHobbs** [comment]
Of course, with a rat I get meat in my inventory, but of course you get what you set in the config

**Comment by Sina30** [comment]
I have what is here, I can't have anything else, but I still use gum_eco

**Comment by outsider31000** [comment]
You need to disable gum eco.

**Comment by Sina30** [comment]
I just tested it again and you don't get anything from rat, but it's not bad because I can't turn gum_eco off, I need it
