### ISSUE TITLE
Giving Items to nearby players

### ISSUE THREAD

**Issue by EagLeTaLoN713** [VORPCORE/VORP-Hunting#16]
Seems that skin an animal with a player nearby will give the obtained items to them as well.  Can be quite a distance away as well. Not sure if this is already an issue, new to github. thanks

**Comment by AndrewR3K** [comment]
This was raised in discord but not in github. Thanks for raising it! I have a pre-release pr up were im testing a potential fix :)

**Comment by AndrewR3K** [comment]
For visibility here is the PR I am referring to https://github.com/VORPCORE/VORP-Hunting/pull/13

**Comment by AndrewR3K** [comment]
Just tested this PR with a friend and it seems to have resolved the issue. Once this is merged, please update and let me know if you still receive this issue. 

Thanks!

**Comment by AndrewR3K** [comment]
@EagLeTaLoN713 Assuming this specific issue has been resolved for you? If so @outsider31000 I think we can close this specific issue.
