### ISSUE TITLE
Issue Selling Large Pelt

### ISSUE THREAD

**Issue by EagLeTaLoN713** [VORPCORE/VORP-Hunting#20]
Can't seem to sell LARGE pelts off the back of the horse. In hand seems to work ok  This happened with both a moose and bison pelt.

**Comment by AndrewR3K** [comment]
Did it give you any errors?

**Comment by EagLeTaLoN713** [comment]
> Did it give you any errors?

https://gyazo.com/cf0765d480cc2a0c33d6bcd3d6496f52
with entity in F8
https://gyazo.com/7a08a754818d2996dc7eadff0f0cd4a1

[-1098441944]  = { name = "Moose", givenItem = { "BigGameMeat" }, givenAmount = { 0 }, money = 8, gold = 0, rolPoints = 0, xp = 3, poorQualityMultiplier = 1.0, goodQualityMultiplier = 1.5, perfectQualityMultiplier = 2, poor = 1868576868, good = 1636891382, perfect = -217731719 },

**Comment by EagLeTaLoN713** [comment]
Another issue, I am unable to sell Angus Ox pelt. [556355544]    = { name = "Angus Ox"   < just reference from the script. Butcher tells me he is unable to buy this animal.  I have checked and double check and can't figure out why butcher wont purchase it.

**Comment by outsider31000** [comment]
make sure the hashes are correct

**Comment by EagLeTaLoN713** [comment]
> make sure the hashes are correct
yeah verified number given and whats in script. 
https://i.gyazo.com/152fa6e1c7dfd34fb672dcbe1d0959d5.png

**Comment by EagLeTaLoN713** [comment]
I know this was closed, but the original issue of not being able to sell LARGE pelts from horseback still exists.  This is the error I get when trying to sell the pelt while its still on my horse. 
NETWORK_GET_NETWORK_ID_FROM_ENTITY: no such entity
NETWORK_GET_ENTITY_FROM_NETWORK_ID: no object by ID 0

**Comment by RizzooTv** [comment]
He's right, large skins are not automatically removed from the horse!

**Comment by outsider31000** [comment]
Is it with all big pelts?

**Comment by EagLeTaLoN713** [comment]
Ive opened another issue on this. I stopped posting on this one as its closed.
