### ISSUE TITLE
Large Pelt from Horseback

### ISSUE THREAD

**Issue by EagLeTaLoN713** [VORPCORE/VORP-Hunting#22]
I made the mistake of commenting on a closed issue.  There is an issue of selling large pelts from horse back.  
I assume this F8 error is from trying to sell it.  

NETWORK_GET_NETWORK_ID_FROM_ENTITY: no such entity
NETWORK_GET_ENTITY_FROM_NETWORK_ID: no object by ID 0

**Comment by EagLeTaLoN713** [comment]
Ive been unsuccessful selling  Alligator, Elk, Ox and Bison pelts from horseback. Ox pelts don't work at all at any level of quality even from hand held.

**Comment by AndrewR3K** [comment]
I can take a look into this, this week. Strange those arent workjng
