### ISSUE TITLE
label instead of item

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/VORP-Hunting#23]
In the notification, for example, if I pick up a fish, which I then also get into the inventory, it says a_c_fishbluegil_01_sm , Blue Gil (Small) should be there, so the label in the database is not the item, please please add that, otherwise it will look so stupid in the notification<3

**Comment by AndrewR3K** [comment]
The notification/name is based on what you have within the config.lua. Did you change yours at all? If so what did you change it too?

```
Config.SmallAnimals = {
    --small animals skin them and sell them at the butcher no need to add them to  CONFIG.ANIMALS
    [989669666]   = { name = "Rat", givenItem = { "meat" }, givenAmount = { 1 }, money = 100, gold = 0, rolPoints = 0, xp = 1 },
    [1458540991]  = { name = "Raccoon", givenItem = { "pelt" }, givenAmount = { 2 }, money = 100, gold = 0, rolPoints = 0, xp = 1 },
    [-1003616053] = { name = "Duck", givenItem = { "feathers" }, givenAmount = { 0 }, money = 100, gold = 0, rolPoints = 0, xp = 1 },

    -- big animals when you skin them it gives you items. if you have it added TO CONFIG.ANIMALS JUST COPY PASTE HERE AND REMOVE THE GIVE MONEY ETC LIKE SHOWN BELOW.
    [1110710183]  = { name = "Deer", givenItem = { "meat" }, givenAmount = { 0 }, money = 0, gold = 0, rolPoints = 0, xp = 1 },
    [-1124266369] = { name = "Bear", givenItem = { "bearHeart", "bearClaws" }, givenAmount = { 1, 3 }, money = 0, gold = 0, rolPoints = 0, xp = 1 }
}
```

**Comment by RizzooTv** [comment]
Of course, I'm using the latest version and have adapted it for me, here's a picture as an example, the ITEM isn't written there (i.e. the label) and it doesn't look so good :D  https://prnt.sc/g2nOxFHdfmYm

**Comment by AndrewR3K** [comment]
Can you please send what your scripts config.lua looks like?

**Comment by RizzooTv** [comment]
https://prnt.sc/zjIJmiyZJrym

**Comment by AndrewR3K** [comment]
Ah ok, I see. 

This is due to how I am leveraging that for the notification. I'll see if I can get it to pull that label from inventory, or at the very least, I can add a new config variable for what's shown.

I'll update here when that's implemented. 

Cheers 😄

**Comment by AndrewR3K** [comment]
This functionality has been added to the latest release :)
