### ISSUE TITLE
You can't sell big skins

### ISSUE THREAD

**Issue by Sina30** [VORPCORE/VORP-Hunting#26]
I just tested it and they don't sell big skins tried a bear "A_C_Bear_01" it says I won't buy that animal that when you have the skin in your hand when you put the big skin on the horse wants says if I want to sell it and then he puts it on the horse, if I have the skin on the horse go to the butcher I can't sell it either

**Comment by AndrewR3K** [comment]
Not quite sure I understand your issue/question here. 

Did you modify the config at all? The last update brought a new addition to it that is required.

If you want to sell the skin that is on your horse, make sure it is next to you when you are selling.

**Comment by Sina30** [comment]
I just took yours and put it on the server didn't change it

I can have it lying next to me it is not for sale small fur can be sold

If you have a large skin in your hand and stand by the horse and then want to put it on the horse, he says to me if I want to sell the skin, but I want to put the skin on the horse

**Comment by outsider31000** [comment]
Then move the horse away from the butcher. Also you sure you updated your config file? Maybe you have wrong hash

**Comment by Sina30** [comment]
Yes, I did that because I uploaded everything from here, I took the hash -1124266369 and then the bear came out, which I wanted and then wanted to test it with the fur and it can't be sold, then I have the new one back deleted the old one I had turned on before and everything works perfectly.
