### ISSUE TITLE
Error While Roping and Killing Cow

### ISSUE THREAD

**Issue by EagLeTaLoN713** [VORPCORE/VORP-Hunting#29]
![image](https://user-images.githubusercontent.com/104523142/171165941-db4c1a5b-93b7-4137-ab6f-13e708180504.png)
Not sure if related but skinned a cow after roping and killing and got this error.

**Comment by EagLeTaLoN713** [comment]
Killed and Skinned an Alligator.  Did not give me the Animal Gathered: notification in console like I did with the cow.

**Comment by DerHobbs** [comment]
Alligator and Cow https://prnt.sc/9-eVK2nkx-Gl
If both work, maybe check your config again

**Comment by EagLeTaLoN713** [comment]
Was the error I got skinning cow resolved?

**Comment by AndrewR3K** [comment]
Can you double check your config for me and make sure you the skinnableAnimals they look like this? 
    [989669666]   = { name = "Rat", givenItem = { "meat" }, givenAmount = { 1 }, givenDisplay = {}, money = 100, gold = 0, rolPoints = 0, xp = 1 },


Main thing is to make sure the skinnable animals have the givenDisplay = {} within it, which might be whats giving you the above error (this was added to the config an update ot two ago)

**Comment by EagLeTaLoN713** [comment]
Yes sir.  
 [989669666]   = { name = "Rat", givenItem = { "consumable_game","pelt" }, givenAmount = { 0,0 }, money = 0.00, gold = 0, rolPoints = 0, xp = 1 },

**Comment by EagLeTaLoN713** [comment]
ahhh missing the given Display.  So i have to redo my whole config.  I just copied it all.  My Bad!
