### ISSUE TITLE
can store 5 pelts or more but only get paid for 3

### ISSUE THREAD

**Issue by crazyvetfam** [VORPCORE/VORP-Hunting#47]
so if u have more then 3 pelts on your horse that's all u get paid for i posted video in discord  u can have 5 but only get paid for 3 also  with newest update seems lots of animals disappearing again.

**Comment by DerHobbs** [comment]
I don't think the animal disappearance is due to vorp_hunting but to Onesync.

On the topic of skins, I can only tell you that we can put 10 skins on the horse and it works perfectly.

**Comment by crazyvetfam** [comment]
![image](https://user-images.githubusercontent.com/88051046/201769123-872f8087-9c2e-4fe8-8d47-1c1e538be28b.png)
![image](https://user-images.githubusercontent.com/88051046/201769146-a106cb08-8f0b-4ca1-8355-9c2d37c10be0.png)
![image](https://user-images.githubusercontent.com/88051046/201769172-67811491-59da-49cf-a656-97996bec8f74.png)
 10 pelts got money for 5  money matches notifications  could it maybe a corrupt down load

**Comment by outsider31000** [comment]
max pelt is only 3.
