### ISSUE TITLE
DataViewNativeGetEventData error

### ISSUE THREAD

**Issue by Sina30** [VORPCORE/VORP-Hunting#7]
That's what I get when I sell an animal at Fell, he doesn't tell me that 

[img]https://i.imgur.com/VHocbyA.png[/img]

**Comment by outsider31000** [comment]
did you rename the file?
do you have a js file in the client folder?

**Comment by Sina30** [comment]
No, it's still vorp_hunting, yes I have it in there, I'm also surprised why he shows me that

**Comment by AndrewR3K** [comment]
When I got this during testing, a server restart fixed this for me and the scripts are then able to access that new js resource properly.

**Comment by Sina30** [comment]
I restarted the server several times in between

**Comment by AndrewR3K** [comment]
oh weird, for me a server restart solved this and it never appeared again.

Can you check your fxmanifest.

- Do you have client/main.js in your clientscripts within fxmanifest section
- Do you have  exports in your fxmanifest
```
exports {
	'DataViewNativeGetEventData'
}
```

**Comment by Sina30** [comment]
oh man I forgot, thank you both

**Comment by AndrewR3K** [comment]
No worries. Happy hunting! 🤠
