### ISSUE TITLE
Config.SmallAnimals it does not work

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/VORP-Hunting#8]
After skinning

[    script:vorp_core] SCRIPT ERROR: @vorp_core/server/class/sv_character.lua:197: attempt to perform arithmetic on a nil value (local 'quantity')
[    script:vorp_core] > addCurrency (@vorp_core/server/class/sv_character.lua:197)
[    script:vorp_core] > ref (@vorp_core/server/class/sv_character.lua:149)
[    script:vorp_core] > handler (@vorp_hunting/server/main.lua:30)
[ script:vorp_hunting] SCRIPT ERROR: error object is not a string
[ script:vorp_hunting] (nil stack trace)SCRIPT ERROR: @vorp_inventory/server/services/inventoryApiService.lua:309: attempt to compare nil with number
[script:vorp_inventor] > ref (@vorp_inventory/vorpInventoryApi.lua:16)
[script:vorp_inventor] > handler (@vorp_hunting/server/main.lua:27)

**Comment by AndrewR3K** [comment]
Did you make any modifications to the SmallAnimals Config object? If so can you share what you changed? Thanks!

**Comment by RizzooTv** [comment]
Absolutely nothing, I just downloaded it and wanted to test it, but there are always these errors after skinning, one error is from a deer, the other from a rat

**Comment by outsider31000** [comment]
I changed it and added the deer or bear but i tested and worked.

**Comment by AndrewR3K** [comment]
Strange, it should be working fine. When I was testing last night it all worked. 

Ill see if I can replicate this error on my server.

**Comment by RizzooTv** [comment]
I just re-downloaded Inventory Lua and Hunting, the same error, unfortunately it doesn't work

**Comment by AndrewR3K** [comment]
I think I see the bug. Making a pr shortly

**Comment by RizzooTv** [comment]
I thank you <3

**Comment by AndrewR3K** [comment]
@outsider31000 Just raised a PR with the fix. My apologies for the bad variable.
